import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { supabase } from "@/lib/supabase";

// GET: Fetch structured AI insights dashboard
export async function GET() {
  const cookieStore = await cookies();
  const userId = cookieStore.get("subsense_session")?.value;

  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const apiKey = process.env.GEMINI_API_KEY;

    // Fetch user's subscriptions
    const { data: activeSubs } = await supabase
      .from("subscriptions")
      .select("*")
      .eq("user_id", userId);

    const subs = activeSubs || [];
    const totalSpend = subs.reduce((sum: number, s: any) => sum + s.price, 0);
    const wasteSubs = subs.filter((s: any) => s.status !== "active");
    const wasteSpend = wasteSubs.reduce((sum: number, s: any) => sum + s.price, 0);
    const annualSpend = subs.reduce((sum: number, s: any) => {
      return sum + (s.billing_frequency === "yearly" ? s.price : s.price * 12);
    }, 0);

    const categoryMap = subs.reduce((acc: Record<string, number>, s: any) => {
      acc[s.category] = (acc[s.category] || 0) + s.price;
      return acc;
    }, {});

    // Fallback if API key is missing
    if (!apiKey) {
      const fallbackScore = totalSpend === 0 ? 100 : Math.max(30, Math.min(100, Math.round(100 - (wasteSpend / totalSpend) * 80)));
      return NextResponse.json({
        summary: `You are spending ₹${totalSpend.toLocaleString("en-IN")} monthly on subscriptions. You have ${subs.length} active platforms.`,
        savings: `You can save up to ₹${wasteSpend.toLocaleString("en-IN")} monthly by optimizing ${wasteSubs.length} idle subscriptions.`,
        healthScore: fallbackScore,
        roast: subs.length > 0
          ? `You have a health score of ${fallbackScore}/100. Jeff Bezos personally thanks you for auto-billing subscriptions you haven't opened in a month.`
          : "Your board is empty. Plug in a bank statement or Gmail so I can find something to roast.",
        recommendations: wasteSubs.length > 0 
          ? [`Cancel ${wasteSubs[0].name} to save ${wasteSubs[0].currency}${wasteSubs[0].price} immediately.`]
          : ["You are clean! Keep auditing to maintain this budget."]
      });
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

    const systemPrompt = `You are SubSense AI, a witty financial optimizer.
Analyze this JSON subscription data:
- Monthly Outlay: ₹${totalSpend}
- Annual Outlay: ₹${annualSpend}
- Flagged Waste: ₹${wasteSpend}
- Categories: ${JSON.stringify(categoryMap)}
- Listing: ${JSON.stringify(subs)}

Generate a structured JSON output with the exact keys:
{
  "summary": "Short 1-2 sentence description of user spending metrics",
  "savings": "Analysis of immediate monthly and annual savings options",
  "healthScore": 0-100 score based on active vs waste outlay ratio,
  "roast": "Brutal, funny, witty roast of the user's spending habits",
  "recommendations": ["Array of 2-3 specific, actionable recommendations"]
}
Return ONLY valid JSON. Do not write any markdown code block wrappers (like \`\`\`json).`;

    const result = await model.generateContent([systemPrompt, "Provide the subscription audit analysis."]);
    const response = await result.response;
    const text = response.text().trim();

    // Clean JSON wrappers if generated by model
    const jsonStr = text.replace(/```json/gi, "").replace(/```/g, "").trim();
    const parsed = JSON.parse(jsonStr);

    return NextResponse.json(parsed);

  } catch (error) {
    console.error("Gemini AI API GET Error:", error);
    return NextResponse.json({ error: "AI completions failed" }, { status: 500 });
  }
}

// POST: Handles assistant chat
export async function POST(request: Request) {
  const cookieStore = await cookies();
  const userId = cookieStore.get("subsense_session")?.value;

  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const body = await request.json();
    const { prompt, action, subscriptions } = body;

    const apiKey = process.env.GEMINI_API_KEY;

    // Retrieve active subscriptions from database if not passed
    let activeSubs = subscriptions;
    if (!activeSubs) {
      const { data } = await supabase
        .from("subscriptions")
        .select("*")
        .eq("user_id", userId);
      activeSubs = data || [];
    }

    const totalSpend = activeSubs.reduce((sum: number, s: any) => sum + s.price, 0);
    const wasteSubs = activeSubs.filter((s: any) => s.status !== "active");
    const wasteSpend = wasteSubs.reduce((sum: number, s: any) => sum + s.price, 0);

    // Fallback if API key is missing
    if (!apiKey) {
      console.warn("GEMINI_API_KEY is missing. Generating rules-based local AI response.");
      
      let text = "";
      
      if (action === "roast") {
        if (activeSubs.length === 0) {
          text = "I can't tell you the truth because your subscription board is empty. Go connect Gmail so I can find something to criticize.";
        } else {
          const firstWaste = wasteSubs[0]?.name || "your unused apps";
          text = `Allan, you are spending ₹${totalSpend.toLocaleString("en-IN")} monthly on subscriptions. You haven't opened ${firstWaste} in over a month, yet you are still happily auto-billing. Jeff Bezos personally thanks you for your charity.`;
        }
      } else if (action === "cancel") {
        const subName = prompt || "the service";
        text = `Sure, I've drafted a cancellation email for your ${subName} subscription. Tapping the Transmit button will send this out immediately, scrubbing ₹${prompt ? activeSubs.find((s: any) => s.name === prompt)?.price || 299 : 299} from your billing cycle.`;
      } else {
        text = `Auditing completed. Discovered ${activeSubs.length} active platforms. You are wasting ₹${wasteSpend} monthly on ${wasteSubs.length} unused or duplicate memberships. Recommended action: Cancel unused subscriptions immediately.`;
      }

      return NextResponse.json({ text, localFallback: true });
    }

    // Real Gemini Chat
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

    let systemPrompt = `You are SubSense, a brilliant, witty, and direct AI financial intelligence assistant.
Your goal is to help users understand their subscription waste, expose their idle spending habits with the humorous/brutal truth, and provide actionable tips to cancel and optimize.
Here is the user's current subscription profile:
- Total Subscriptions: ${activeSubs.length}
- Total Monthly Outlay: ₹${totalSpend}
- Flagged Waste Outlay: ₹${wasteSpend}
- Flagged Waste Items: ${JSON.stringify(wasteSubs)}
- Full Listing: ${JSON.stringify(activeSubs)}

Generate a direct response matching the user request. Keep your answers brief (under 3-4 sentences max), punchy, and highly analytical. Avoid using generic emojis.`;

    const userPrompt = prompt || "Analyze my subscriptions and give me a summary of waste.";

    const result = await model.generateContent([systemPrompt, userPrompt]);
    const response = await result.response;
    const text = response.text().trim();

    return NextResponse.json({ text });

  } catch (error) {
    console.error("Gemini AI API POST Error:", error);
    return NextResponse.json({ error: "AI completions failed" }, { status: 500 });
  }
}
